### ISSUE TITLE
Error in retrieving manifest

### ISSUE THREAD

**Issue by chicc0** [truedread/pymsl#1]
Given this... 

id = sys.argv[1]
user_auth_data = {
        'scheme': 'EMAIL_PASSWORD',
        'authdata': {
                'email': 'xxxx@gmail.com',                   
                'password': 'xxxxx' 
                            }                       
}

client = pymsl.MslClient(user_auth_data)           manif = client.load_manifest([id])                 print manif

Runnig 
python script.py 80249081
I get this weird error

pymsl.exceptions.ManifestError: {u'result': {u'errorDetails': u'This title is not available to watch instantly', u'errorDisplayMessage': u'This title is not available to watch instantly. Please try another title.', u'data': u'com.netflix.api.service.APILookupException: Reference: 80249081, Error Message : java.lang.String cannot be cast to java.lang.Integer', u'errorExternalCode': 50230418, u'errorSubCode': 1331}, u'success': False}

Is there any problem with it?

**Comment by MythodeaLoL** [comment]
Have you tried with another ESN?
try
`NFCDCH-02-`

**Comment by chicc0** [comment]
Thats already Default..
